### ISSUE TITLE
Call to undefined session

### ISSUE THREAD

**Issue by wergh** [PitonCMS/Session#4]
I try to use your sessionHandler, but can't make it work!

I don't use composer, so i install the SessionHandler.php, and create the table in my db.

Then i try to do this... i will write you what i can see:
`
```
$dsn = 'mysql:host=localhost;dbname=bd_prueba'; 

try{ 

$dbh = new PDO($dsn, 'user_prueba', 'Abc123.'); 

}  catch (PDOException $e) { 

    echo 'Conection Fail: ' . $e->getMessage(); 

} 

var_dump($dbh); 

require_once 'SessionHandler.php';

$config['secondsUntilExpiration'] = 7200; // 30 minutes

$Session = new SessionHandler($dbh, $config);

var_dump($Session);

$Session->setData('nombre', 'Carlos');
```
 `

When i run this code i can see this....
`
```
object(PDO)#1 (0) { } object(SessionHandler)#2 (0) { } 

Fatal error: Call to undefined method SessionHandler::setData() in /var/www/vhosts/....../sessions.php on line 9
````

Can you help me?

Ty very much!

**Comment by wolfmoritz** [comment]
It looks like the object is not being instantiated. Try using the namespace as in:

    $Session = new WolfMoritz\Session\SessionHandler($dbh, $config);

**Comment by wolfmoritz** [comment]
By the way, you also need to provide a salt in the config array. If the custom session handler was being instantiated it would have thrown an error that the salt was not set. In your config array:

    $config['salt'] = 'akjfao8ygoa8hba9707lakusdof87'; // USE YOUR OWN STRING

**Comment by wergh** [comment]
FIXED! 
Thank you very much mate!
